### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by nurettinselcuk** [pedazo-m/Pointer#2]
Hello, you have done a grate job but I could not run it.

I am trying on console 
pointer.move_mouse_to_element('.a-last')
and then calling pointer.click_element('.a-last')
but no action.

By the way, the class injected successfull.

**Comment by nurettinselcuk** [comment]
OK I understand, it is my bad :)

**Comment by Rolleas** [comment]
I haven't tested in a long time. if you are still interested i can see the
script

ср, 1 дек. 2021 г. в 04:31, nurettinselcuk ***@***.***>:
